config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products do
    resources :comments
  end
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :payments, only: [:create]

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  get 'simple_pages/landing_page'

  root 'simple_pages#index'

  post 'simple_pages/thank_you'

  mount ActionCable.server => '/cable'

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Cabo Verde Peanut Butter</title>

  <!-- see 3.9 for info about these three tags-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body data-spy="scroll" data-target=".navbar">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div> <!--to make the navigation bar stretch across the entire page-->

      <!--hamburger menu-->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="projectName navbar-brand" id="logo">
          <p>  <%= image_tag("cabov2.png",  class: "img-responsive", style: 'display:inline') %>
          <%= link_to "CABO VERDE PEANUT BUTTER", simple_pages_index_path %></p>
      </div> <!--end projectName -->

      </div> <!--end navbar-header -->

      <div class="navbar-collapse collapse" id="nav">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "HOME", simple_pages_index_path %></li>
          <li><%= link_to "OUR STORY", simple_pages_about_path %></li>
          <li><%= link_to "CONTACT", simple_pages_contact_path %></li>
          <li><%= link_to "PRODUCTS", products_path %></li>
          <li><%= form_with(url: products_path, method: 'get', local: true) do |form| %>
            <%= form.text_field :q, id: 'q', value: params[:q] %>
            <%= form.submit 'Search' %>
            <% end %></li>


          </ul>


        </div>

        <div class="nav pull-right" id="login">

            <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
            <%= link_to('LOG IN / BECOME A MEMBER', new_user_session_path) %>
            <% end %>
          </div>

      </div>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if notice %>
  <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>
</body>

<div id="prgm" >
  <%= yield %>
</div>

<footer>

  &copy; 2018 Cabo Verde Peanut Butter
</footer>

</html>